#pragma once

#define ESPTELEPATHY_IDENTITY_PREFIX "ESPTELEPATHY_IDENTITY "
#define ESPTELEPATHY_TELEMETRY_SCHEMA_VERSION "0-dev"
#define ESPTELEPATHY_BUILD_CONFIG_ID "foundation-v1"

#ifndef ESPTELEPATHY_GIT_SHA
#define ESPTELEPATHY_GIT_SHA "unknown"
#endif

#ifndef ESPTELEPATHY_BUILD_TARGET
#define ESPTELEPATHY_BUILD_TARGET "unknown"
#endif
